### ISSUE TITLE
async_art_update issues

### ISSUE THREAD

**Issue by HorkusMcLoink** [NickWaterton/samsung-tv-ws-api#2]
Hi, I am NoNewsTY from Reddit. I went through and re-followed all the steps of the readme.txt and I think I had missed installing Pillow the first time around. Unfortunately that didn't resolve my issues. Here's what I have done:
After making sure everything was installed correctly, ran the async script I had been working with yesterday, which included the path to my token which I set through that other script I mentioned. I saw different updates in the logs and it successfully displayed the photos, so thought we were on the right track. However, I left the room for 7 mins, sleep happens at 5 mins, and when the tv woke, it was stuck on the last photo again. Here is a sample of the logs:

`INFO:Main:Program Started
INFO:Main.monitor_and_display:Start Monitoring
INFO:Main.monitor_and_display:Started
INFO:Main.monitor_and_display:using matte: flexible_black
INFO:Main.monitor_and_display:API version: 4.3.4.0
INFO:Main.monitor_and_display:Current artwork is: SAM-F0222
INFO:Main.monitor_and_display:files in directory: /Users/XXXXX/Pictures/FrameTVSlideshow: ['sands.jpg', (more photos, etc)]
INFO:Main.PIL_methods:Checking uploaded files list using PIL
INFO:Main.PIL_methods:loading files: ['sands.jpg', (more photos, etc)]
INFO:Main.PIL_methods:getting My Photos list
INFO:Main.PIL_methods:downloading My Photos thumbnails
INFO:Main.PIL_methods:got 2 thumbnails
INFO:Main.PIL_methods:checking thumbnails against 34 files, please wait...
INFO:Main.monitor_and_display:checking directory: /Users/XXXXX/Pictures/FrameTVSlideshow every 0:00:15
INFO:Main.monitor_and_display:adding files to tv : ['sands.jpg', (more photos, etc)]
INFO:Main.monitor_and_display:uploading : sands.jpg to tv
INFO:Main.monitor_and_display:uploaded : sands.jpg to tv as MY_F0055
(It does this for the remaining photos)
INFO:Main.monitor_and_display:selecting tv art: content_id: MY_F0060
INFO:Main.monitor_and_display:checking directory: /Users/XXXXX/Pictures/FrameTVSlideshow every 0:00:15
INFO:Main.monitor_and_display:doing slideshow update, after 0:00:15
(it continues doing this, displaying the slideshow as expected. But then it shows the following and loops through that until terminated)
INFO:Main.monitor_and_display:artmode or tv is off`

I saw that you updated the code today, so I downloaded it, ran it, got the issue I get when unable to set the token:
`INFO:Main:Program Started
INFO:Main.monitor_and_display:Start Monitoring
ERROR:Main.monitor_and_display:failed to connect with TV: {'event': 'ms.channel.timeOut'}`

So I ran my script to set my token and inserted the path to the token into today's version of your code. The last photo from earlier is still shown and now won't update at all (historically I could at least resume the slideshow when I did my token trick)

`INFO:Main:Program Started
INFO:Main.monitor_and_display:Start Monitoring
INFO:Main.monitor_and_display:Started
INFO:Main.monitor_and_display:using matte: flexible_black
INFO:Main.monitor_and_display:API version: 4.3.4.0
INFO:Main.monitor_and_display:Current artwork is: MY_F0058
INFO:Main.monitor_and_display:files in directory: /Users/XXXXX/Pictures/FrameTVSlideshow: ['sands.jpg', (photos)]
INFO:Main.PIL_methods:Checking uploaded files list using PIL
INFO:Main.PIL_methods:loading files: ['sands.jpg',(photos)]
INFO:Main.PIL_methods:getting My Photos list
INFO:Main.PIL_methods:downloading My Photos thumbnails
INFO:Main.PIL_methods:got 36 thumbnails
INFO:Main.PIL_methods:checking thumbnails against 34 files, please wait...
INFO:Main.PIL_methods:0% complete
INFO:Main.PIL_methods:found uploaded file: sands.jpg as MY_F0075
INFO:Main.PIL_methods:9% complete
INFO:Main.PIL_methods:19% complete
INFO:Main.PIL_methods:29% complete
INFO:Main.PIL_methods:39% complete
INFO:Main.PIL_methods:49% complete
INFO:Main.PIL_methods:59% complete
INFO:Main.PIL_methods:69% complete
INFO:Main.PIL_methods:79% complete
INFO:Main.PIL_methods:89% complete
INFO:Main.monitor_and_display:checking directory: /Users/XXXXX/Pictures/FrameTVSlideshow every 0:00:15
WARNING:Main.monitor_and_display:error in check_dir: no close frame received or sent`

And it loops through those last 2 lines until termination. 
What do you think of this? As I mentioned, I'm happy to set up a session with both of my Frame TVs running, to troubleshoot in real time if that's helpful. And once we get this running, definitely sending some coffee your way!

**Comment by NickWaterton** [comment]
I will take another look tomorrow, and let you know.

I guess I need to add the token thing as well.

**Comment by HorkusMcLoink** [comment]
Fixed in https://github.com/NickWaterton/samsung-tv-ws-api/issues/3
